prog_name: repolite
pull_with_rebase: false
repos:
-   repo_alias: mv-ddr
    repo_branch: master
    repo_depth: 0
    repo_enable: true
    repo_has_lfs_files: false
    repo_hash: bfcf62051be835f725005bb5137928f7c27b792e
    repo_init_submodules: false
    repo_install: false
    repo_name: mv-ddr-marvell
    repo_opts: []
    repo_remote: origin
    repo_url: https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell.git
    repo_use_rebase: false
-   repo_alias: mv-utils
    repo_branch: master
    repo_depth: 0
    repo_enable: true
    repo_has_lfs_files: false
    repo_hash: a3e1c67bb378e1d8a938e1b826cb602af83628d2
    repo_init_submodules: false
    repo_install: false
    repo_name: A3700-utils-marvell
    repo_opts: []
    repo_remote: origin
    repo_url: https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell.git
    repo_use_rebase: false
-   repo_alias: mv-bins
    repo_branch: binaries-marvell-armada-18.12
    repo_depth: 0
    repo_enable: false
    repo_has_lfs_files: false
    repo_hash: null
    repo_init_submodules: false
    repo_install: false
    repo_name: binaries-marvell
    repo_opts: []
    repo_remote: origin
    repo_url: https://github.com/MarvellEmbeddedProcessors/binaries-marvell.git
    repo_use_rebase: false
-   repo_alias: null
    repo_branch: CRYPTOPP_8_7_0
    repo_depth: 0
    repo_enable: true
    repo_has_lfs_files: false
    repo_hash: 511806c0eba8ba5b5cedd4b4a814e96df92864a6
    repo_init_submodules: false
    repo_install: false
    repo_name: cryptopp
    repo_opts: []
    repo_remote: origin
    repo_url: https://github.com/weidai11/cryptopp.git
    repo_use_rebase: false
-   repo_alias: mox-boot
    repo_branch: v2022.06.11
    repo_depth: 0
    repo_enable: true
    repo_has_lfs_files: false
    repo_hash: 406454d882e78a7273054f8e6040fff18a5fe131
    repo_init_submodules: false
    repo_install: false
    repo_name: mox-boot-builder
    repo_opts: []
    repo_remote: origin
    repo_url: https://gitlab.nic.cz/turris/mox-boot-builder.git
    repo_use_rebase: false
-   repo_alias: null
    repo_branch: v2022.10
    repo_depth: 0
    repo_enable: true
    repo_has_lfs_files: false
    repo_hash: 4debc57a3da6c3f4d3f89a637e99206f4cea0a96
    repo_init_submodules: false
    repo_install: false
    repo_name: u-boot
    repo_opts: []
    repo_remote: origin
    repo_url: https://github.com/u-boot/u-boot.git
    repo_use_rebase: false
-   repo_alias: tfa
    repo_branch: lts-v2.8
    repo_depth: 0
    repo_enable: true
    repo_has_lfs_files: false
    repo_hash: b2dc24a412933340cd93f9dcbfc5c559db4048b3
    repo_init_submodules: false
    repo_install: false
    repo_name: trusted-firmware-a
    repo_opts: []
    repo_remote: origin
    repo_url: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git
    repo_use_rebase: false
top_dir: ext
