prog_name: repolite
top_dir: ext  # local directory path for enabled repositories
pull_with_rebase: false  # use --ff-only if false
# add new repo_name sections as needed
repos:
  - repo_name: rkbin
    repo_alias: null
    repo_url: https://github.com/rockchip-linux/rkbin
    repo_depth: 1
    repo_remote: origin
    repo_opts: []
    repo_branch: master
    repo_hash: null
    repo_use_rebase: false
    repo_has_lfs_files: false
    repo_init_submodules: false
    repo_install: false
    repo_enable: true
  - repo_name: u-boot
    repo_alias: null
    repo_url: https://github.com/u-boot/u-boot.git
    repo_depth: 0
    repo_remote: origin
    repo_opts: []
    repo_branch: master
    repo_hash: v2023.10
    repo_use_rebase: false
    repo_has_lfs_files: false
    repo_init_submodules: false
    repo_install: false
    repo_enable: true
  - repo_name: trusted-firmware-a
    repo_alias: tfa
    repo_url: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git
    repo_depth: 0
    repo_remote: origin
    repo_opts: []
    repo_branch: master
    repo_hash: v2.10.0
    repo_use_rebase: false
    repo_has_lfs_files: false
    repo_init_submodules: false
    repo_install: false
    repo_enable: true
